import assert from "node:assert/strict";
import { resolve } from "node:path";
import { test } from "node:test";
import { chromium } from "playwright";
import { DashboardService } from "../src/dashboard/service.js";
import { createDashboardServer } from "../src/dashboard/server.js";
import { dashboardConfig, dashboardDirectory, dashboardFetch } from "./dashboard-fixtures.js";

test("configuration separates the complete mockup from the real read-only Azure prompt", async (t) => {
  const settings = dashboardConfig(dashboardDirectory(t), { AZURE_OPENAI_VOICE: "cedar" });
  const upstream = dashboardFetch();
  const server = createDashboardServer(settings, new DashboardService(settings, upstream.request), resolve("dashboard"));
  const port = await server.listen();
  t.after(() => server.close());
  const browser = await chromium.launch();
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${port}`);
  await page.locator('input[name="dashboard-token"]').fill(settings.DASHBOARD_TOKEN);
  await page.getByRole("button", { name: "Conectar", exact: true }).click();
  await page.getByRole("link", { name: "Configuración", exact: true }).click();
  await page.getByText("cedar", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Instrucciones", exact: true }).click();
  const realPrompt = page.getByRole("textbox", { name: "Prompt real de Azure" });
  assert.match(await realPrompt.inputValue(), /very occasional brief acknowledgement/);
  assert.equal(await realPrompt.getAttribute("readonly"), "");
  await page.getByRole("button", { name: "Demo visual", exact: true }).click();
  await page.getByText("Clínica Vera Salud", { exact: true }).waitFor();
  assert.match(await page.locator(".content").innerText(), /965/);
  assert.equal(await realPrompt.count(), 0);
  await page.getByRole("button", { name: "Instrucciones", exact: true }).click();
  assert.match(await page.getByRole("textbox", { name: "Prompt demo" }).inputValue(), /Clínica Vera Salud/);
  assert.equal(await page.getByRole("slider").count(), 6);
  await page.getByText("Advertir una vez", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Acciones", exact: true }).click();
  assert.equal(await page.getByRole("switch").count(), 6);
  await page.getByText("Doctoralia", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Cumplimiento", exact: true }).click();
  await page.getByText("99,4% registrado", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Datos reales", exact: true }).click();
  assert.doesNotMatch(await page.locator(".content").innerText(), /Vera Salud|Doctoralia|99,4%/);
  assert.ok(upstream.requests.every(({ method }) => method === "GET"));
  assert.deepEqual(errors, []);
});
