import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test } from "node:test";
import { chromium } from "playwright";
import { DashboardService } from "../src/dashboard/service.js";
import { createDashboardServer } from "../src/dashboard/server.js";
import { dashboardConfig, dashboardFetch, writeDashboardRecord } from "./dashboard-fixtures.js";

test("the original dashboard runs end-to-end with read-only sources, empty states and live metadata updates", { timeout: 60_000 }, async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dashboard-browser-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  writeDashboardRecord(directory);
  const settings = dashboardConfig(directory);
  const upstream = dashboardFetch();
  const server = createDashboardServer(settings, new DashboardService(settings, upstream.request), resolve("dashboard"));
  const port = await server.listen();
  t.after(() => server.close());
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors: string[] = [];
  const requests: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (request) => requests.push(request.url()));
  const base = `http://127.0.0.1:${port}`;
  await page.goto(base);
  assert.equal(await page.getByRole("heading", { name: "Clinica Sintetica" }).count(), 0);
  await page.locator('input[name="dashboard-token"]').fill(settings.DASHBOARD_TOKEN);
  await page.getByRole("button", { name: "Conectar", exact: true }).click();
  await page.getByRole("heading", { name: "Clinica Sintetica", exact: true, level: 2 }).waitFor();
  assert.doesNotMatch(await page.locator("body").innerText(), /Vera Salud|Vicente|NaN|undefined/);
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
  await page.getByRole("link", { name: "Clientes", exact: true }).click();
  await page.getByText("Sin paciente seleccionado", { exact: true }).waitFor();
  await page.getByRole("searchbox", { name: "Nombre o teléfono del paciente" }).fill("Ada");
  await page.getByRole("button", { name: "Buscar", exact: true }).click();
  await page.getByRole("heading", { name: "Ada Sintetica Prueba", exact: true }).waitFor();
  await page.getByText("Profesional de prueba · Sede de prueba", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Nuevo paciente", exact: true }).isDisabled(), true);
  assert.doesNotMatch(await page.locator("body").innerText(), /00000000T|PRIVATE_|1980-06-15/);
  await page.getByRole("link", { name: "Llamadas", exact: true }).click();
  await page.getByRole("button", { name: "Ver analítica", exact: true }).click();
  await page.getByText("G.711 mu-law · 8 kHz · mono", { exact: true }).waitFor();
  assert.doesNotMatch(await page.locator("body").innerText(), /Opus 48k|PRIVATE_|MOS [0-9]|NaN/);
  await page.getByRole("button", { name: "Señales", exact: true }).click();
  await page.getByText("Sentimiento e intenciones: no disponibles", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Ver mapa", exact: true }).click();
  await page.locator(".map__node").first().click();
  await page.getByRole("button", { name: "Ver más en Clientes", exact: true }).click();
  await page.getByRole("heading", { name: "Ada Sintetica Prueba", exact: true }).waitFor();
  assert.match(page.url(), /#\/clientes\/PATIENT_TEST$/);
  await page.getByRole("link", { name: "Configuración", exact: true }).click();
  await page.getByRole("button", { name: "Instrucciones", exact: true }).click();
  await page.getByText("Gestionadas en el backend", { exact: true }).waitFor();
  assert.equal(await page.locator("textarea").count(), 0);
  await page.getByRole("link", { name: "Llamadas", exact: true }).click();
  writeDashboardRecord(directory, "new-open-test", { ended: false, accepted: false });
  await page.getByText("Llamada new-open-test", { exact: true }).waitFor({ timeout: 12_000 });
  assert.ok(upstream.requests.every((request) => request.method === "GET"));
  assert.ok(requests.every((url) => url.startsWith(base)), "No patient-linked avatars, fonts or third-party requests");
  assert.deepEqual(errors, []);
  await page.getByRole("button", { name: "Desconectar", exact: true }).click();
  await page.getByRole("button", { name: "Conectar", exact: true }).waitFor();
  assert.doesNotMatch(await page.locator("body").innerText(), /Ada Sintetica|new-open-test/);
});

test("source outages and zero calls render unavailable states rather than demo values", { timeout: 30_000 }, async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dashboard-browser-empty-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const settings = dashboardConfig(directory);
  const server = createDashboardServer(settings,
    new DashboardService(settings, dashboardFetch({ fail: true }).request), resolve("dashboard"));
  const port = await server.listen();
  t.after(() => server.close());
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${port}`);
  await page.locator('input[name="dashboard-token"]').fill(settings.DASHBOARD_TOKEN);
  await page.getByRole("button", { name: "Conectar", exact: true }).click();
  await page.getByRole("heading", { name: "Fuentes de datos", exact: true }).waitFor();
  assert.match(await page.locator("body").innerText(), /prosper_http_503/);
  assert.doesNotMatch(await page.locator("body").innerText(), /NaN|undefined|PRIVATE_UPSTREAM_FAILURE|342|965/);
  await page.getByRole("link", { name: "Llamadas", exact: true }).click();
  await page.getByRole("button", { name: "Ver mapa", exact: true }).click();
  await page.getByText("Ninguna llamada con este filtro.", { exact: true }).waitFor();
  await page.getByRole("link", { name: "Clientes", exact: true }).click();
  await page.getByText("Sin paciente seleccionado", { exact: true }).waitFor();
  assert.deepEqual(errors, []);
});
